src/Entity/Candidat.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use DH\DoctrineAuditBundle\Annotation\Auditable;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource()
 * @ORM\Entity(repositoryClass="App\Repository\CandidatRepository")
 * @Auditable()
 */
class Candidat
{

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="date")
     */
    private $date_naissance;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lieu_naissance;

    /**
     * @ORM\Column(type="string", length=1)
     */
    private $sexe;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $prefeture;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $diplome;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lieu_centre_concour;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $etablissement_de_provenance;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $jury;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $filier_serie;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $matier_eliminer;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $amphi;

    /**
     * @ORM\Column(type="string", length=5, nullable=true)
     */
    private $numero_salle;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $semestre;



    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Evenement", inversedBy="candidats")
     */
    private $evenement;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getLieuNaissance(): ?string
    {
        return $this->lieu_naissance;
    }

    public function setLieuNaissance(string $lieu_naissance): self
    {
        $this->lieu_naissance = $lieu_naissance;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getPrefeture(): ?string
    {
        return $this->prefeture;
    }

    public function setPrefeture(?string $prefeture): self
    {
        $this->prefeture = $prefeture;

        return $this;
    }

    public function getDiplome(): ?string
    {
        return $this->diplome;
    }

    public function setDiplome(?string $diplome): self
    {
        $this->diplome = $diplome;

        return $this;
    }

    public function getLieuCentreConcour(): ?string
    {
        return $this->lieu_centre_concour;
    }

    public function setLieuCentreConcour(string $lieu_centre_concour): self
    {
        $this->lieu_centre_concour = $lieu_centre_concour;

        return $this;
    }

    public function getEtablissementDeProvenance(): ?string
    {
        return $this->etablissement_de_provenance;
    }

    public function setEtablissementDeProvenance(string $etablissement_de_provenance): self
    {
        $this->etablissement_de_provenance = $etablissement_de_provenance;

        return $this;
    }

    public function getJury(): ?string
    {
        return $this->jury;
    }

    public function setJury(?string $jury): self
    {
        $this->jury = $jury;

        return $this;
    }

    public function getFilierSerie(): ?string
    {
        return $this->filier_serie;
    }

    public function setFilierSerie(?string $filier_serie): self
    {
        $this->filier_serie = $filier_serie;

        return $this;
    }

    public function getMatierEliminer(): ?string
    {
        return $this->matier_eliminer;
    }

    public function setMatierEliminer(?string $matier_eliminer): self
    {
        $this->matier_eliminer = $matier_eliminer;

        return $this;
    }

    public function getAmphi(): ?string
    {
        return $this->amphi;
    }

    public function setAmphi(?string $amphi): self
    {
        $this->amphi = $amphi;

        return $this;
    }

    public function getNumeroSalle(): ?string
    {
        return $this->numero_salle;
    }

    public function setNumeroSalle(?string $numero_salle): self
    {
        $this->numero_salle = $numero_salle;

        return $this;
    }

    public function getSemestre(): ?string
    {
        return $this->semestre;
    }

    public function setSemestre(?string $semestre): self
    {
        $this->semestre = $semestre;

        return $this;
    }



    public function getEvenement(): ?Evenement
    {
        return $this->evenement;
    }

    public function setEvenement(?Evenement $evenement): self
    {
        $this->evenement = $evenement;

        return $this;
    }
}

src/Form/CandidatType.php
<?php

namespace App\Form;

use App\Entity\Candidat;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CandidatType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('date_naissance')
            ->add('lieu_naissance')
            ->add('sexe')
            ->add('prefeture')
            ->add('diplome')
            ->add('lieu_centre_concour')
            ->add('etablissement_de_provenance')
            ->add('jury')
            ->add('filier_serie')
            ->add('matier_eliminer')
            ->add('amphi')
            ->add('numero_salle')
            ->add('semestre')
            ->add('datecreation')
            ->add('createBy')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Candidat::class,
        ]);
    }
}

src/Controller/CandidatController.php
<?php

namespace App\Controller;

use App\Entity\Candidat;
use App\Form\CandidatType;
use App\Repository\CandidatRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/candidat")
 */
class CandidatController extends AbstractController
{
    /**
     * @Route("/", name="candidat_index", methods={"GET"})
     */
    public function index(CandidatRepository $candidatRepository): Response
    {
        return $this->render('candidat/index.html.twig', [
            'candidats' => $candidatRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="candidat_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $candidat = new Candidat();
        $form = $this->createForm(CandidatType::class, $candidat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($candidat);
            $entityManager->flush();

            return $this->redirectToRoute('candidat_index');
        }

        return $this->render('candidat/new.html.twig', [
            'candidat' => $candidat,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="candidat_show", methods={"GET"})
     */
    public function show(Candidat $candidat): Response
    {
        return $this->render('candidat/show.html.twig', [
            'candidat' => $candidat,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="candidat_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Candidat $candidat): Response
    {
        $form = $this->createForm(CandidatType::class, $candidat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('candidat_index');
        }

        return $this->render('candidat/edit.html.twig', [
            'candidat' => $candidat,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="candidat_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Candidat $candidat): Response
    {
        if ($this->isCsrfTokenValid('delete'.$candidat->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($candidat);
            $entityManager->flush();
        }

        return $this->redirectToRoute('candidat_index');
    }
}

templates/candidat/_delete_form.html.twig
<form method="post" action="{{ path('candidat_delete', {'id': candidat.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ candidat.id) }}">
    <button class="btn">Delete</button>
</form>

templates/candidat/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/candidat/edit.html.twig
{% extends 'base.html.twig' %}


{% block title %}Edit Candidat{% endblock %}

{% block body %}
    <h1>Edit Candidat</h1>

    {{ include('candidat/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('candidat_index') }}">back to list</a>

    {{ include('candidat/_delete_form.html.twig') }}
{% endblock %}

templates/candidat/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Candidat index{% endblock %}


{% block body %}
    <h1>Candidat index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Date_naissance</th>
                <th>Lieu_naissance</th>
                <th>Sexe</th>
                <th>Prefeture</th>
                <th>Diplome</th>
                <th>Lieu_centre_concour</th>
                <th>Etablissement_de_provenance</th>
                <th>Jury</th>
                <th>Filier_serie</th>
                <th>Matier_eliminer</th>
                <th>Amphi</th>
                <th>Numero_salle</th>
                <th>Semestre</th>
                <th>Datecreation</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for candidat in candidats %}
            <tr>
                <td>{{ candidat.id }}</td>
                <td>{{ candidat.nom }}</td>
                <td>{{ candidat.prenom }}</td>
                <td>{{ candidat.dateNaissance ? candidat.dateNaissance|date('Y-m-d') : '' }}</td>
                <td>{{ candidat.lieuNaissance }}</td>
                <td>{{ candidat.sexe }}</td>
                <td>{{ candidat.prefeture }}</td>
                <td>{{ candidat.diplome }}</td>
                <td>{{ candidat.lieuCentreConcour }}</td>
                <td>{{ candidat.etablissementDeProvenance }}</td>
                <td>{{ candidat.jury }}</td>
                <td>{{ candidat.filierSerie }}</td>
                <td>{{ candidat.matierEliminer }}</td>
                <td>{{ candidat.amphi }}</td>
                <td>{{ candidat.numeroSalle }}</td>
                <td>{{ candidat.semestre }}</td>
                <td>{{ candidat.datecreation ? candidat.datecreation|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('candidat_show', {'id': candidat.id}) }}">show</a>
                    <a href="{{ path('candidat_edit', {'id': candidat.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="18">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('candidat_new') }}">Create new</a>
{% endblock %}

templates/candidat/new.html.twig
{% extends 'base.html.twig' %}


{% block title %}New Candidat{% endblock %}

{% block body %}
    <h1>Create new Candidat</h1>

    {{ include('candidat/_form.html.twig') }}

    <a href="{{ path('candidat_index') }}">back to list</a>
{% endblock %}

templates/candidat/show.html.twig
{% extends 'base.html.twig' %}


{% block title %}Candidat{% endblock %}

{% block body %}
    <h1>Candidat</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ candidat.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ candidat.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ candidat.prenom }}</td>
            </tr>
            <tr>
                <th>Date_naissance</th>
                <td>{{ candidat.dateNaissance ? candidat.dateNaissance|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Lieu_naissance</th>
                <td>{{ candidat.lieuNaissance }}</td>
            </tr>
            <tr>
                <th>Sexe</th>
                <td>{{ candidat.sexe }}</td>
            </tr>
            <tr>
                <th>Prefeture</th>
                <td>{{ candidat.prefeture }}</td>
            </tr>
            <tr>
                <th>Diplome</th>
                <td>{{ candidat.diplome }}</td>
            </tr>
            <tr>
                <th>Lieu_centre_concour</th>
                <td>{{ candidat.lieuCentreConcour }}</td>
            </tr>
            <tr>
                <th>Etablissement_de_provenance</th>
                <td>{{ candidat.etablissementDeProvenance }}</td>
            </tr>
            <tr>
                <th>Jury</th>
                <td>{{ candidat.jury }}</td>
            </tr>
            <tr>
                <th>Filier_serie</th>
                <td>{{ candidat.filierSerie }}</td>
            </tr>
            <tr>
                <th>Matier_eliminer</th>
                <td>{{ candidat.matierEliminer }}</td>
            </tr>
            <tr>
                <th>Amphi</th>
                <td>{{ candidat.amphi }}</td>
            </tr>
            <tr>
                <th>Numero_salle</th>
                <td>{{ candidat.numeroSalle }}</td>
            </tr>
            <tr>
                <th>Semestre</th>
                <td>{{ candidat.semestre }}</td>
            </tr>
            <tr>
                <th>Datecreation</th>
                <td>{{ candidat.datecreation ? candidat.datecreation|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('candidat_index') }}">back to list</a>

    <a href="{{ path('candidat_edit', {'id': candidat.id}) }}">edit</a>

    {{ include('candidat/_delete_form.html.twig') }}
{% endblock %}